apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
spec:
  template:
    spec:
      containers:
        - name: coffee
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 9000
            - name: dlv
              containerPort: 7000
          # Disable probes — hitting a breakpoint pauses the process and
          # will trigger pod restarts if probes are active
          readinessProbe: null
          livenessProbe: null
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
