apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coffee.yaml
  - rbac.yaml
configMapGenerator:
  - name: coffee-config
    files:
      - config.yaml=../../../../app/coffee/configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
