// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: greeter/coffee/v1/coffee.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCoffeeBrew = "/coffee.v1.Coffee/Brew"
const OperationCoffeeCheck = "/coffee.v1.Coffee/Check"

type CoffeeHTTPServer interface {
	// Brew Start brewing a cup. Returns an instance_id you can poll.
	Brew(context.Context, *BrewRequest) (*BrewReply, error)
	// Check Check on a brewing cup by instance_id.
	Check(context.Context, *CheckRequest) (*CheckReply, error)
}

func RegisterCoffeeHTTPServer(s *http.Server, srv CoffeeHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/coffee", _Coffee_Brew0_HTTP_Handler(srv))
	r.GET("/v1/coffee/{instance_id}", _Coffee_Check0_HTTP_Handler(srv))
}

func _Coffee_Brew0_HTTP_Handler(srv CoffeeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BrewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCoffeeBrew)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Brew(ctx, req.(*BrewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BrewReply)
		return ctx.Result(200, reply)
	}
}

func _Coffee_Check0_HTTP_Handler(srv CoffeeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCoffeeCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Check(ctx, req.(*CheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckReply)
		return ctx.Result(200, reply)
	}
}

type CoffeeHTTPClient interface {
	// Brew Start brewing a cup. Returns an instance_id you can poll.
	Brew(ctx context.Context, req *BrewRequest, opts ...http.CallOption) (rsp *BrewReply, err error)
	// Check Check on a brewing cup by instance_id.
	Check(ctx context.Context, req *CheckRequest, opts ...http.CallOption) (rsp *CheckReply, err error)
}

type CoffeeHTTPClientImpl struct {
	cc *http.Client
}

func NewCoffeeHTTPClient(client *http.Client) CoffeeHTTPClient {
	return &CoffeeHTTPClientImpl{client}
}

// Brew Start brewing a cup. Returns an instance_id you can poll.
func (c *CoffeeHTTPClientImpl) Brew(ctx context.Context, in *BrewRequest, opts ...http.CallOption) (*BrewReply, error) {
	var out BrewReply
	pattern := "/v1/coffee"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCoffeeBrew))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Check Check on a brewing cup by instance_id.
func (c *CoffeeHTTPClientImpl) Check(ctx context.Context, in *CheckRequest, opts ...http.CallOption) (*CheckReply, error) {
	var out CheckReply
	pattern := "/v1/coffee/{instance_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCoffeeCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
