// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: greeter/coffee/v1/coffee.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coffee_Brew_FullMethodName  = "/coffee.v1.Coffee/Brew"
	Coffee_Check_FullMethodName = "/coffee.v1.Coffee/Check"
)

// CoffeeClient is the client API for Coffee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Coffee is a tiny Dapr Workflow demo: brew a cup, then check on it.
type CoffeeClient interface {
	// Start brewing a cup. Returns an instance_id you can poll.
	Brew(ctx context.Context, in *BrewRequest, opts ...grpc.CallOption) (*BrewReply, error)
	// Check on a brewing cup by instance_id.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckReply, error)
}

type coffeeClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeClient(cc grpc.ClientConnInterface) CoffeeClient {
	return &coffeeClient{cc}
}

func (c *coffeeClient) Brew(ctx context.Context, in *BrewRequest, opts ...grpc.CallOption) (*BrewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrewReply)
	err := c.cc.Invoke(ctx, Coffee_Brew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckReply)
	err := c.cc.Invoke(ctx, Coffee_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeeServer is the server API for Coffee service.
// All implementations must embed UnimplementedCoffeeServer
// for forward compatibility.
//
// Coffee is a tiny Dapr Workflow demo: brew a cup, then check on it.
type CoffeeServer interface {
	// Start brewing a cup. Returns an instance_id you can poll.
	Brew(context.Context, *BrewRequest) (*BrewReply, error)
	// Check on a brewing cup by instance_id.
	Check(context.Context, *CheckRequest) (*CheckReply, error)
	mustEmbedUnimplementedCoffeeServer()
}

// UnimplementedCoffeeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeServer struct{}

func (UnimplementedCoffeeServer) Brew(context.Context, *BrewRequest) (*BrewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Brew not implemented")
}
func (UnimplementedCoffeeServer) Check(context.Context, *CheckRequest) (*CheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedCoffeeServer) mustEmbedUnimplementedCoffeeServer() {}
func (UnimplementedCoffeeServer) testEmbeddedByValue()                {}

// UnsafeCoffeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeServer will
// result in compilation errors.
type UnsafeCoffeeServer interface {
	mustEmbedUnimplementedCoffeeServer()
}

func RegisterCoffeeServer(s grpc.ServiceRegistrar, srv CoffeeServer) {
	// If the following call pancis, it indicates UnimplementedCoffeeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coffee_ServiceDesc, srv)
}

func _Coffee_Brew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServer).Brew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coffee_Brew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServer).Brew(ctx, req.(*BrewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coffee_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coffee_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coffee_ServiceDesc is the grpc.ServiceDesc for Coffee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coffee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coffee.v1.Coffee",
	HandlerType: (*CoffeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Brew",
			Handler:    _Coffee_Brew_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Coffee_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter/coffee/v1/coffee.proto",
}
