// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: coffee/v1/coffee.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beans         string                 `protobuf:"bytes,1,opt,name=beans,proto3" json:"beans,omitempty"` // e.g. "arabica"
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`   // "small", "medium", "large"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrewRequest) Reset() {
	*x = BrewRequest{}
	mi := &file_coffee_v1_coffee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrewRequest) ProtoMessage() {}

func (x *BrewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_v1_coffee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrewRequest.ProtoReflect.Descriptor instead.
func (*BrewRequest) Descriptor() ([]byte, []int) {
	return file_coffee_v1_coffee_proto_rawDescGZIP(), []int{0}
}

func (x *BrewRequest) GetBeans() string {
	if x != nil {
		return x.Beans
	}
	return ""
}

func (x *BrewRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type BrewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrewReply) Reset() {
	*x = BrewReply{}
	mi := &file_coffee_v1_coffee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrewReply) ProtoMessage() {}

func (x *BrewReply) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_v1_coffee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrewReply.ProtoReflect.Descriptor instead.
func (*BrewReply) Descriptor() ([]byte, []int) {
	return file_coffee_v1_coffee_proto_rawDescGZIP(), []int{1}
}

func (x *BrewReply) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_coffee_v1_coffee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_v1_coffee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_coffee_v1_coffee_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type CheckReply struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// RUNNING, COMPLETED, FAILED, etc.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Final coffee description once status == COMPLETED.
	Cup           string `protobuf:"bytes,3,opt,name=cup,proto3" json:"cup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReply) Reset() {
	*x = CheckReply{}
	mi := &file_coffee_v1_coffee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReply) ProtoMessage() {}

func (x *CheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_v1_coffee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReply.ProtoReflect.Descriptor instead.
func (*CheckReply) Descriptor() ([]byte, []int) {
	return file_coffee_v1_coffee_proto_rawDescGZIP(), []int{3}
}

func (x *CheckReply) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CheckReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckReply) GetCup() string {
	if x != nil {
		return x.Cup
	}
	return ""
}

var File_coffee_v1_coffee_proto protoreflect.FileDescriptor

const file_coffee_v1_coffee_proto_rawDesc = "" +
	"\n" +
	"\x16coffee/v1/coffee.proto\x12\tcoffee.v1\x1a\x1cgoogle/api/annotations.proto\"7\n" +
	"\vBrewRequest\x12\x14\n" +
	"\x05beans\x18\x01 \x01(\tR\x05beans\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\",\n" +
	"\tBrewReply\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"/\n" +
	"\fCheckRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"W\n" +
	"\n" +
	"CheckReply\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03cup\x18\x03 \x01(\tR\x03cup2\xb0\x01\n" +
	"\x06Coffee\x12K\n" +
	"\x04Brew\x12\x16.coffee.v1.BrewRequest\x1a\x14.coffee.v1.BrewReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/coffee\x12Y\n" +
	"\x05Check\x12\x17.coffee.v1.CheckRequest\x1a\x15.coffee.v1.CheckReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/coffee/{instance_id}BD\n" +
	"\x18dev.kratos.api.coffee.v1B\rCoffeeProtoV1P\x01Z\x17coffee/api/coffee/v1;v1b\x06proto3"

var (
	file_coffee_v1_coffee_proto_rawDescOnce sync.Once
	file_coffee_v1_coffee_proto_rawDescData []byte
)

func file_coffee_v1_coffee_proto_rawDescGZIP() []byte {
	file_coffee_v1_coffee_proto_rawDescOnce.Do(func() {
		file_coffee_v1_coffee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coffee_v1_coffee_proto_rawDesc), len(file_coffee_v1_coffee_proto_rawDesc)))
	})
	return file_coffee_v1_coffee_proto_rawDescData
}

var file_coffee_v1_coffee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coffee_v1_coffee_proto_goTypes = []any{
	(*BrewRequest)(nil),  // 0: coffee.v1.BrewRequest
	(*BrewReply)(nil),    // 1: coffee.v1.BrewReply
	(*CheckRequest)(nil), // 2: coffee.v1.CheckRequest
	(*CheckReply)(nil),   // 3: coffee.v1.CheckReply
}
var file_coffee_v1_coffee_proto_depIdxs = []int32{
	0, // 0: coffee.v1.Coffee.Brew:input_type -> coffee.v1.BrewRequest
	2, // 1: coffee.v1.Coffee.Check:input_type -> coffee.v1.CheckRequest
	1, // 2: coffee.v1.Coffee.Brew:output_type -> coffee.v1.BrewReply
	3, // 3: coffee.v1.Coffee.Check:output_type -> coffee.v1.CheckReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coffee_v1_coffee_proto_init() }
func file_coffee_v1_coffee_proto_init() {
	if File_coffee_v1_coffee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coffee_v1_coffee_proto_rawDesc), len(file_coffee_v1_coffee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coffee_v1_coffee_proto_goTypes,
		DependencyIndexes: file_coffee_v1_coffee_proto_depIdxs,
		MessageInfos:      file_coffee_v1_coffee_proto_msgTypes,
	}.Build()
	File_coffee_v1_coffee_proto = out.File
	file_coffee_v1_coffee_proto_goTypes = nil
	file_coffee_v1_coffee_proto_depIdxs = nil
}
