// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dapr/go-sdk/client"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"greeter/app/greeter/internal/biz"
	"greeter/app/greeter/internal/conf"
	"greeter/app/greeter/internal/data"
	"greeter/app/greeter/internal/server"
	"greeter/app/greeter/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, clientClient client.Client, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	workflowClient := data.NewWorkflowClient(clientClient)
	coffeeUsecase, cleanup2, err := biz.NewCoffeeUsecase(workflowClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	coffeeService := service.NewCoffeeService(coffeeUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, coffeeService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, coffeeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
