apiVersion: v2
name: coffee-deps
version: 0.1.0
type: application
description: Local dev dependencies (Redis) for coffee.
dependencies:
  - name: redis
    version: 0.27.4
    repository: oci://registry-1.docker.io/cloudpirates
