redis:
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        memory: 64Mi
  metrics:
    enabled: false
