// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: greeter/orders/v1/orders.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,2,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderRequest) Reset() {
	*x = StartOrderRequest{}
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderRequest) ProtoMessage() {}

func (x *StartOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderRequest.ProtoReflect.Descriptor instead.
func (*StartOrderRequest) Descriptor() ([]byte, []int) {
	return file_greeter_orders_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *StartOrderRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *StartOrderRequest) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type StartOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrderReply) Reset() {
	*x = StartOrderReply{}
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrderReply) ProtoMessage() {}

func (x *StartOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrderReply.ProtoReflect.Descriptor instead.
func (*StartOrderReply) Descriptor() ([]byte, []int) {
	return file_greeter_orders_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *StartOrderReply) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_greeter_orders_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetOrderReply struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// RUNNING, COMPLETED, FAILED, TERMINATED, etc.
	RuntimeStatus string `protobuf:"bytes,2,opt,name=runtime_status,json=runtimeStatus,proto3" json:"runtime_status,omitempty"`
	Output        string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_orders_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_greeter_orders_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderReply) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetOrderReply) GetRuntimeStatus() string {
	if x != nil {
		return x.RuntimeStatus
	}
	return ""
}

func (x *GetOrderReply) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_greeter_orders_v1_orders_proto protoreflect.FileDescriptor

const file_greeter_orders_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x1egreeter/orders/v1/orders.proto\x12\torders.v1\x1a\x1cgoogle/api/annotations.proto\"O\n" +
	"\x11StartOrderRequest\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x02 \x01(\x01R\ttotalCost\"2\n" +
	"\x0fStartOrderReply\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"2\n" +
	"\x0fGetOrderRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"o\n" +
	"\rGetOrderReply\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eruntime_status\x18\x02 \x01(\tR\rruntimeStatus\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output2\xcb\x01\n" +
	"\x06Orders\x12]\n" +
	"\n" +
	"StartOrder\x12\x1c.orders.v1.StartOrderRequest\x1a\x1a.orders.v1.StartOrderReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12b\n" +
	"\bGetOrder\x12\x1a.orders.v1.GetOrderRequest\x1a\x18.orders.v1.GetOrderReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/orders/{instance_id}BM\n" +
	"\x18dev.kratos.api.orders.v1B\rOrdersProtoV1P\x01Z greeter/api/greeter/orders/v1;v1b\x06proto3"

var (
	file_greeter_orders_v1_orders_proto_rawDescOnce sync.Once
	file_greeter_orders_v1_orders_proto_rawDescData []byte
)

func file_greeter_orders_v1_orders_proto_rawDescGZIP() []byte {
	file_greeter_orders_v1_orders_proto_rawDescOnce.Do(func() {
		file_greeter_orders_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greeter_orders_v1_orders_proto_rawDesc), len(file_greeter_orders_v1_orders_proto_rawDesc)))
	})
	return file_greeter_orders_v1_orders_proto_rawDescData
}

var file_greeter_orders_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_greeter_orders_v1_orders_proto_goTypes = []any{
	(*StartOrderRequest)(nil), // 0: orders.v1.StartOrderRequest
	(*StartOrderReply)(nil),   // 1: orders.v1.StartOrderReply
	(*GetOrderRequest)(nil),   // 2: orders.v1.GetOrderRequest
	(*GetOrderReply)(nil),     // 3: orders.v1.GetOrderReply
}
var file_greeter_orders_v1_orders_proto_depIdxs = []int32{
	0, // 0: orders.v1.Orders.StartOrder:input_type -> orders.v1.StartOrderRequest
	2, // 1: orders.v1.Orders.GetOrder:input_type -> orders.v1.GetOrderRequest
	1, // 2: orders.v1.Orders.StartOrder:output_type -> orders.v1.StartOrderReply
	3, // 3: orders.v1.Orders.GetOrder:output_type -> orders.v1.GetOrderReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greeter_orders_v1_orders_proto_init() }
func file_greeter_orders_v1_orders_proto_init() {
	if File_greeter_orders_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greeter_orders_v1_orders_proto_rawDesc), len(file_greeter_orders_v1_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_orders_v1_orders_proto_goTypes,
		DependencyIndexes: file_greeter_orders_v1_orders_proto_depIdxs,
		MessageInfos:      file_greeter_orders_v1_orders_proto_msgTypes,
	}.Build()
	File_greeter_orders_v1_orders_proto = out.File
	file_greeter_orders_v1_orders_proto_goTypes = nil
	file_greeter_orders_v1_orders_proto_depIdxs = nil
}
