// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"coffee/app/coffee/internal/biz"
	"coffee/app/coffee/internal/conf"
	"coffee/app/coffee/internal/data"
	"coffee/app/coffee/internal/server"
	"coffee/app/coffee/internal/service"
	"github.com/dapr/go-sdk/client"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, clientClient client.Client, logger log.Logger) (*kratos.App, func(), error) {
	workflowClient := data.NewWorkflowClient(clientClient)
	publisher := data.NewPublisher(clientClient)
	pubSubUsecase := biz.NewPubSubUsecase(publisher, logger)
	coffeeUsecase, cleanup, err := biz.NewCoffeeUsecase(workflowClient, pubSubUsecase, logger)
	if err != nil {
		return nil, nil, err
	}
	coffeeService := service.NewCoffeeService(coffeeUsecase)
	grpcServer := server.NewGRPCServer(confServer, coffeeService, logger)
	httpServer := server.NewHTTPServer(confServer, coffeeService, pubSubUsecase, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
